require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
end

target 'App' do
  capacitor_pods

  # Firebase pods
  use_modular_headers!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'      # Optional
  pod 'Firebase/Messaging'      # Optional
end

post_install do |installer|
  assertDeploymentTarget(installer)
end