apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_URL: amRiYzpteXNxbDovL3Jvb3Q6SVFDanhXZHNVc3FQc0lYVW1NRU9KSUF3ZkdlcktUaFhAc3dpdGNoYmFjay5wcm94eS5ybHd5Lm5ldDoyMTYyNS9yYWlsd2F5
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: SVFDanhXZHNVc3FQc0lYVW1NRU9KSUF3ZkdlcktUaFg=
  
